/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query ListCycles($first: Int, $after: String, $filter: CycleFilter) {\n    cycles(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        number\n        startsAt\n        endsAt\n        completedAt\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.ListCyclesDocument,
    "\n  query ListDocuments($first: Int, $after: String, $filter: DocumentFilter) {\n    documents(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        title\n        slugId\n        updatedAt\n        project {\n          id\n          name\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.ListDocumentsDocument,
    "\n  query GetDocument($id: String!) {\n    document(id: $id) {\n      id\n      title\n      slugId\n      content\n      updatedAt\n      project {\n        id\n        name\n      }\n      creator {\n        id\n        name\n        displayName\n      }\n    }\n  }\n": typeof types.GetDocumentDocument,
    "\n  query GetIssueBranch($id: String!) {\n    issue(id: $id) {\n      id\n      branchName\n    }\n  }\n": typeof types.GetIssueBranchDocument,
    "\n  query ListComments($issueId: String!, $first: Int, $after: String) {\n    issue(id: $issueId) {\n      comments(first: $first, after: $after) {\n        nodes {\n          id\n          body\n          createdAt\n          parentId\n          user {\n            name\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n": typeof types.ListCommentsDocument,
    "\n  query CommentIssueId($id: String!) {\n    comment(id: $id) {\n      issueId\n    }\n  }\n": typeof types.CommentIssueIdDocument,
    "\n  query IssueCopy($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      url\n      branchName\n    }\n  }\n": typeof types.IssueCopyDocument,
    "\n  query ViewerFavorites {\n    favorites {\n      nodes {\n        id\n        type\n        issue {\n          id\n          identifier\n        }\n      }\n    }\n  }\n": typeof types.ViewerFavoritesDocument,
    "\n  query GetIssue($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      title\n      description\n      url\n      branchName\n      priority\n      estimate\n      dueDate\n      createdAt\n      state {\n        id\n        name\n        type\n      }\n      assignee {\n        id\n        name\n        displayName\n        email\n      }\n      labels {\n        nodes {\n          id\n          name\n          color\n        }\n      }\n      project {\n        id\n        name\n      }\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      attachments {\n        nodes {\n          id\n          title\n          url\n        }\n      }\n    }\n  }\n": typeof types.GetIssueDocument,
    "\n  query IssueHistory($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      history {\n        nodes {\n          id\n          createdAt\n          actors {\n            id\n            name\n            displayName\n          }\n          updatedDescription\n          fromTitle\n          toTitle\n          fromState {\n            id\n            name\n          }\n          toState {\n            id\n            name\n          }\n          fromDueDate\n          toDueDate\n          toConvertedProject {\n            id\n            name\n          }\n          trashed\n          archived\n          autoArchived\n          autoClosed\n        }\n      }\n    }\n  }\n": typeof types.IssueHistoryDocument,
    "\n  query ListIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.ListIssuesDocument,
    "\n  query MeIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.MeIssuesDocument,
    "\n  query SearchIssues($term: String!, $first: Int, $after: String, $filter: IssueFilter) {\n    searchIssues(term: $term, first: $first, after: $after, filter: $filter) {\n      nodes {\n        identifier\n        title\n        state { name }\n        assignee { displayName }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.SearchIssuesDocument,
    "\n  query IssueRelations($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      relations {\n        nodes {\n          id\n          type\n          relatedIssue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n      inverseRelations {\n        nodes {\n          id\n          type\n          issue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n    }\n  }\n": typeof types.IssueRelationsDocument,
    "\n  fragment IssueFields on Issue {\n    identifier\n    title\n    state { name }\n    assignee { displayName }\n    priority\n  }\n": typeof types.IssueFieldsFragmentDoc,
    "\n  query ProjectMilestones($id: String!) {\n    project(id: $id) {\n      projectMilestones {\n        nodes {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.ProjectMilestonesDocument,
    "\n  query ListLabels($first: Int, $after: String, $filter: IssueLabelFilter) {\n    issueLabels(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        color\n        parent {\n          id\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.ListLabelsDocument,
    "\n  query ListProjectMilestones($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      projectMilestones(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          targetDate\n          description\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n": typeof types.ListProjectMilestonesDocument,
    "\n  query GetProjectMilestone($id: String!) {\n    projectMilestone(id: $id) {\n      id\n      name\n      targetDate\n      description\n      progress\n      sortOrder\n      project {\n        id\n        name\n      }\n    }\n  }\n": typeof types.GetProjectMilestoneDocument,
    "\n  query GetProject($id: String!) {\n    project(id: $id) {\n      id\n      name\n      description\n      state\n      url\n      startDate\n      targetDate\n      lead {\n        id\n        name\n        displayName\n      }\n      teams {\n        nodes {\n          id\n          name\n          key\n        }\n      }\n      members {\n        nodes {\n          id\n          name\n          displayName\n        }\n      }\n    }\n  }\n": typeof types.GetProjectDocument,
    "\n  query ProjectLabels($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      labels(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          color\n          parent {\n            id\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n": typeof types.ProjectLabelsDocument,
    "\n  query ListStatuses($first: Int, $after: String, $filter: WorkflowStateFilter) {\n    workflowStates(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        type\n        color\n        position\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.ListStatusesDocument,
    "\n  query ListUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      nodes {\n        id\n        name\n        displayName\n        email\n        active\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": typeof types.ListUsersDocument,
    "\n  query GetUser($id: String!) {\n    user(id: $id) {\n      id\n      name\n      displayName\n      email\n      active\n      url\n      avatarUrl\n    }\n  }\n": typeof types.GetUserDocument,
};
const documents: Documents = {
    "\n  query ListCycles($first: Int, $after: String, $filter: CycleFilter) {\n    cycles(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        number\n        startsAt\n        endsAt\n        completedAt\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.ListCyclesDocument,
    "\n  query ListDocuments($first: Int, $after: String, $filter: DocumentFilter) {\n    documents(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        title\n        slugId\n        updatedAt\n        project {\n          id\n          name\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.ListDocumentsDocument,
    "\n  query GetDocument($id: String!) {\n    document(id: $id) {\n      id\n      title\n      slugId\n      content\n      updatedAt\n      project {\n        id\n        name\n      }\n      creator {\n        id\n        name\n        displayName\n      }\n    }\n  }\n": types.GetDocumentDocument,
    "\n  query GetIssueBranch($id: String!) {\n    issue(id: $id) {\n      id\n      branchName\n    }\n  }\n": types.GetIssueBranchDocument,
    "\n  query ListComments($issueId: String!, $first: Int, $after: String) {\n    issue(id: $issueId) {\n      comments(first: $first, after: $after) {\n        nodes {\n          id\n          body\n          createdAt\n          parentId\n          user {\n            name\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n": types.ListCommentsDocument,
    "\n  query CommentIssueId($id: String!) {\n    comment(id: $id) {\n      issueId\n    }\n  }\n": types.CommentIssueIdDocument,
    "\n  query IssueCopy($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      url\n      branchName\n    }\n  }\n": types.IssueCopyDocument,
    "\n  query ViewerFavorites {\n    favorites {\n      nodes {\n        id\n        type\n        issue {\n          id\n          identifier\n        }\n      }\n    }\n  }\n": types.ViewerFavoritesDocument,
    "\n  query GetIssue($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      title\n      description\n      url\n      branchName\n      priority\n      estimate\n      dueDate\n      createdAt\n      state {\n        id\n        name\n        type\n      }\n      assignee {\n        id\n        name\n        displayName\n        email\n      }\n      labels {\n        nodes {\n          id\n          name\n          color\n        }\n      }\n      project {\n        id\n        name\n      }\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      attachments {\n        nodes {\n          id\n          title\n          url\n        }\n      }\n    }\n  }\n": types.GetIssueDocument,
    "\n  query IssueHistory($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      history {\n        nodes {\n          id\n          createdAt\n          actors {\n            id\n            name\n            displayName\n          }\n          updatedDescription\n          fromTitle\n          toTitle\n          fromState {\n            id\n            name\n          }\n          toState {\n            id\n            name\n          }\n          fromDueDate\n          toDueDate\n          toConvertedProject {\n            id\n            name\n          }\n          trashed\n          archived\n          autoArchived\n          autoClosed\n        }\n      }\n    }\n  }\n": types.IssueHistoryDocument,
    "\n  query ListIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.ListIssuesDocument,
    "\n  query MeIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.MeIssuesDocument,
    "\n  query SearchIssues($term: String!, $first: Int, $after: String, $filter: IssueFilter) {\n    searchIssues(term: $term, first: $first, after: $after, filter: $filter) {\n      nodes {\n        identifier\n        title\n        state { name }\n        assignee { displayName }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.SearchIssuesDocument,
    "\n  query IssueRelations($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      relations {\n        nodes {\n          id\n          type\n          relatedIssue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n      inverseRelations {\n        nodes {\n          id\n          type\n          issue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n    }\n  }\n": types.IssueRelationsDocument,
    "\n  fragment IssueFields on Issue {\n    identifier\n    title\n    state { name }\n    assignee { displayName }\n    priority\n  }\n": types.IssueFieldsFragmentDoc,
    "\n  query ProjectMilestones($id: String!) {\n    project(id: $id) {\n      projectMilestones {\n        nodes {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.ProjectMilestonesDocument,
    "\n  query ListLabels($first: Int, $after: String, $filter: IssueLabelFilter) {\n    issueLabels(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        color\n        parent {\n          id\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.ListLabelsDocument,
    "\n  query ListProjectMilestones($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      projectMilestones(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          targetDate\n          description\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n": types.ListProjectMilestonesDocument,
    "\n  query GetProjectMilestone($id: String!) {\n    projectMilestone(id: $id) {\n      id\n      name\n      targetDate\n      description\n      progress\n      sortOrder\n      project {\n        id\n        name\n      }\n    }\n  }\n": types.GetProjectMilestoneDocument,
    "\n  query GetProject($id: String!) {\n    project(id: $id) {\n      id\n      name\n      description\n      state\n      url\n      startDate\n      targetDate\n      lead {\n        id\n        name\n        displayName\n      }\n      teams {\n        nodes {\n          id\n          name\n          key\n        }\n      }\n      members {\n        nodes {\n          id\n          name\n          displayName\n        }\n      }\n    }\n  }\n": types.GetProjectDocument,
    "\n  query ProjectLabels($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      labels(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          color\n          parent {\n            id\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n": types.ProjectLabelsDocument,
    "\n  query ListStatuses($first: Int, $after: String, $filter: WorkflowStateFilter) {\n    workflowStates(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        type\n        color\n        position\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.ListStatusesDocument,
    "\n  query ListUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      nodes {\n        id\n        name\n        displayName\n        email\n        active\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n": types.ListUsersDocument,
    "\n  query GetUser($id: String!) {\n    user(id: $id) {\n      id\n      name\n      displayName\n      email\n      active\n      url\n      avatarUrl\n    }\n  }\n": types.GetUserDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListCycles($first: Int, $after: String, $filter: CycleFilter) {\n    cycles(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        number\n        startsAt\n        endsAt\n        completedAt\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListCycles($first: Int, $after: String, $filter: CycleFilter) {\n    cycles(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        number\n        startsAt\n        endsAt\n        completedAt\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListDocuments($first: Int, $after: String, $filter: DocumentFilter) {\n    documents(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        title\n        slugId\n        updatedAt\n        project {\n          id\n          name\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListDocuments($first: Int, $after: String, $filter: DocumentFilter) {\n    documents(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        title\n        slugId\n        updatedAt\n        project {\n          id\n          name\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDocument($id: String!) {\n    document(id: $id) {\n      id\n      title\n      slugId\n      content\n      updatedAt\n      project {\n        id\n        name\n      }\n      creator {\n        id\n        name\n        displayName\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetDocument($id: String!) {\n    document(id: $id) {\n      id\n      title\n      slugId\n      content\n      updatedAt\n      project {\n        id\n        name\n      }\n      creator {\n        id\n        name\n        displayName\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetIssueBranch($id: String!) {\n    issue(id: $id) {\n      id\n      branchName\n    }\n  }\n"): (typeof documents)["\n  query GetIssueBranch($id: String!) {\n    issue(id: $id) {\n      id\n      branchName\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListComments($issueId: String!, $first: Int, $after: String) {\n    issue(id: $issueId) {\n      comments(first: $first, after: $after) {\n        nodes {\n          id\n          body\n          createdAt\n          parentId\n          user {\n            name\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListComments($issueId: String!, $first: Int, $after: String) {\n    issue(id: $issueId) {\n      comments(first: $first, after: $after) {\n        nodes {\n          id\n          body\n          createdAt\n          parentId\n          user {\n            name\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CommentIssueId($id: String!) {\n    comment(id: $id) {\n      issueId\n    }\n  }\n"): (typeof documents)["\n  query CommentIssueId($id: String!) {\n    comment(id: $id) {\n      issueId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query IssueCopy($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      url\n      branchName\n    }\n  }\n"): (typeof documents)["\n  query IssueCopy($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      url\n      branchName\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ViewerFavorites {\n    favorites {\n      nodes {\n        id\n        type\n        issue {\n          id\n          identifier\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ViewerFavorites {\n    favorites {\n      nodes {\n        id\n        type\n        issue {\n          id\n          identifier\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetIssue($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      title\n      description\n      url\n      branchName\n      priority\n      estimate\n      dueDate\n      createdAt\n      state {\n        id\n        name\n        type\n      }\n      assignee {\n        id\n        name\n        displayName\n        email\n      }\n      labels {\n        nodes {\n          id\n          name\n          color\n        }\n      }\n      project {\n        id\n        name\n      }\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      attachments {\n        nodes {\n          id\n          title\n          url\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetIssue($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      title\n      description\n      url\n      branchName\n      priority\n      estimate\n      dueDate\n      createdAt\n      state {\n        id\n        name\n        type\n      }\n      assignee {\n        id\n        name\n        displayName\n        email\n      }\n      labels {\n        nodes {\n          id\n          name\n          color\n        }\n      }\n      project {\n        id\n        name\n      }\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      attachments {\n        nodes {\n          id\n          title\n          url\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query IssueHistory($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      history {\n        nodes {\n          id\n          createdAt\n          actors {\n            id\n            name\n            displayName\n          }\n          updatedDescription\n          fromTitle\n          toTitle\n          fromState {\n            id\n            name\n          }\n          toState {\n            id\n            name\n          }\n          fromDueDate\n          toDueDate\n          toConvertedProject {\n            id\n            name\n          }\n          trashed\n          archived\n          autoArchived\n          autoClosed\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query IssueHistory($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      history {\n        nodes {\n          id\n          createdAt\n          actors {\n            id\n            name\n            displayName\n          }\n          updatedDescription\n          fromTitle\n          toTitle\n          fromState {\n            id\n            name\n          }\n          toState {\n            id\n            name\n          }\n          fromDueDate\n          toDueDate\n          toConvertedProject {\n            id\n            name\n          }\n          trashed\n          archived\n          autoArchived\n          autoClosed\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MeIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query MeIssues($first: Int, $after: String, $filter: IssueFilter) {\n    issues(first: $first, after: $after, filter: $filter) {\n      nodes {\n        ...IssueFields\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SearchIssues($term: String!, $first: Int, $after: String, $filter: IssueFilter) {\n    searchIssues(term: $term, first: $first, after: $after, filter: $filter) {\n      nodes {\n        identifier\n        title\n        state { name }\n        assignee { displayName }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query SearchIssues($term: String!, $first: Int, $after: String, $filter: IssueFilter) {\n    searchIssues(term: $term, first: $first, after: $after, filter: $filter) {\n      nodes {\n        identifier\n        title\n        state { name }\n        assignee { displayName }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query IssueRelations($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      relations {\n        nodes {\n          id\n          type\n          relatedIssue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n      inverseRelations {\n        nodes {\n          id\n          type\n          issue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query IssueRelations($id: String!) {\n    issue(id: $id) {\n      id\n      identifier\n      parent {\n        id\n        identifier\n        title\n      }\n      children {\n        nodes {\n          id\n          identifier\n          title\n        }\n      }\n      relations {\n        nodes {\n          id\n          type\n          relatedIssue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n      inverseRelations {\n        nodes {\n          id\n          type\n          issue {\n            id\n            identifier\n            title\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment IssueFields on Issue {\n    identifier\n    title\n    state { name }\n    assignee { displayName }\n    priority\n  }\n"): (typeof documents)["\n  fragment IssueFields on Issue {\n    identifier\n    title\n    state { name }\n    assignee { displayName }\n    priority\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProjectMilestones($id: String!) {\n    project(id: $id) {\n      projectMilestones {\n        nodes {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProjectMilestones($id: String!) {\n    project(id: $id) {\n      projectMilestones {\n        nodes {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListLabels($first: Int, $after: String, $filter: IssueLabelFilter) {\n    issueLabels(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        color\n        parent {\n          id\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListLabels($first: Int, $after: String, $filter: IssueLabelFilter) {\n    issueLabels(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        color\n        parent {\n          id\n        }\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListProjectMilestones($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      projectMilestones(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          targetDate\n          description\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListProjectMilestones($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      projectMilestones(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          targetDate\n          description\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProjectMilestone($id: String!) {\n    projectMilestone(id: $id) {\n      id\n      name\n      targetDate\n      description\n      progress\n      sortOrder\n      project {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProjectMilestone($id: String!) {\n    projectMilestone(id: $id) {\n      id\n      name\n      targetDate\n      description\n      progress\n      sortOrder\n      project {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProject($id: String!) {\n    project(id: $id) {\n      id\n      name\n      description\n      state\n      url\n      startDate\n      targetDate\n      lead {\n        id\n        name\n        displayName\n      }\n      teams {\n        nodes {\n          id\n          name\n          key\n        }\n      }\n      members {\n        nodes {\n          id\n          name\n          displayName\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetProject($id: String!) {\n    project(id: $id) {\n      id\n      name\n      description\n      state\n      url\n      startDate\n      targetDate\n      lead {\n        id\n        name\n        displayName\n      }\n      teams {\n        nodes {\n          id\n          name\n          key\n        }\n      }\n      members {\n        nodes {\n          id\n          name\n          displayName\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProjectLabels($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      labels(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          color\n          parent {\n            id\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProjectLabels($id: String!, $first: Int, $after: String) {\n    project(id: $id) {\n      labels(first: $first, after: $after) {\n        nodes {\n          id\n          name\n          color\n          parent {\n            id\n          }\n        }\n        pageInfo {\n          hasNextPage\n          endCursor\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListStatuses($first: Int, $after: String, $filter: WorkflowStateFilter) {\n    workflowStates(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        type\n        color\n        position\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListStatuses($first: Int, $after: String, $filter: WorkflowStateFilter) {\n    workflowStates(first: $first, after: $after, filter: $filter) {\n      nodes {\n        id\n        name\n        type\n        color\n        position\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ListUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      nodes {\n        id\n        name\n        displayName\n        email\n        active\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"): (typeof documents)["\n  query ListUsers($first: Int, $after: String) {\n    users(first: $first, after: $after) {\n      nodes {\n        id\n        name\n        displayName\n        email\n        active\n      }\n      pageInfo {\n        hasNextPage\n        endCursor\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUser($id: String!) {\n    user(id: $id) {\n      id\n      name\n      displayName\n      email\n      active\n      url\n      avatarUrl\n    }\n  }\n"): (typeof documents)["\n  query GetUser($id: String!) {\n    user(id: $id) {\n      id\n      name\n      displayName\n      email\n      active\n      url\n      avatarUrl\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;